[theme]
primaryColor="#F63366"
backgroundColor="#f5f5f5"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

body {
    background-color: #f5f5f5;
}

header {
    background-color: #0071bc;
    color: #fff;
}

.stButton button {
    background-color: #0071bc;
    color: #fff;
}

.stTextInput input[type="text"], .stTextArea textarea {
    border-color: #0071bc;
}

.stMultiSelect label, .stRadio label, .stCheckbox label {
    color: #000;
}

.stSelectbox select {
    background-color: #fff;
    color: #000;
    border-color: #0071bc;
}
